server:
  port: 8083

spring:
  application:
    name: ride-management-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ridelink_ride

ridelink:
  jwt:
    secret: RideLinkSuperSecretKeyForDevelopmentOnly123456789
  services:
    driver-service-url: http://localhost:8082
    fare-service-url: http://localhost:8084

  geocoding:
    nominatim-url: https://nominatim.openstreetmap.org
    country-codes: lk
    user-agent: RideLink/1.0 (student project)

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ridelink: INFO
